name: Build Workflow
run-name: Building commit ${{github.sha}}

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    env:
      BUILD_TYPE: Release
      Qt5_DIR: "/opt/Qt/5.15.2/gcc_64"
      VTK_DIR: "/opt/VTK-9.1.0/lib/cmake/vtk-9.1"
      CFITSIO_DIR: "/opt/cfitsio-4.3.0"
      BOOST_DIR: "/opt/boost_1_78_0"

    steps:       
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Code
            Utils

      - name: Prepare
        env:
          KEYS: ${{secrets.KEYS}}
        run: echo $KEYS | base64 --decode > Code/src/authkeys.h

      - name: Configure
        run: > 
          cmake -S ${{github.workspace}}/Code
          -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_PREFIX_PATH=${{env.Qt5_DIR}}
          -DVTK_DIR=${{env.VTK_DIR}}
          -DCFITSIO_ROOT_DIR=${{env.CFITSIO_DIR}}
          -DBOOST_ROOT=${{env.BOOST_DIR}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build
