name: CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    env:
      BUILD_TYPE: Release

    steps:       
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Code

      - name: Prepare
        env:
          KEYS: ${{secrets.KEYS}}
        run: echo $KEYS | base64 -d > Code/src/authkeys.h

      - name: Configure
        run: > 
          cmake -GNinja
          -S ${{github.workspace}}/Code
          -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_PREFIX_PATH=${{vars.Qt5_DIR}}
          -DCMAKE_CXX_FLAGS_INIT="-fuse-ld=gold"
          -DVTK_DIR=${{vars.VTK_DIR}}
          -DCFITSIO_ROOT_DIR=${{vars.CFITSIO_DIR}}
          -DBOOST_ROOT=${{vars.BOOST_DIR}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --parallel
      
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: Binary
          path: ${{github.workspace}}/build/ViaLacteaVisualAnalytics
          retention-days: 1

  release:
    needs: build
    runs-on: [self-hosted, linux, x64]

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Code
            Utils
      
      - name: Get binary
        uses: actions/download-artifact@v4
        with:
          name: Binary
      
      - name: Prepare
        shell: bash
        run: |
          echo "${{vars.Qt5_DIR}}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${{vars.VTK_DIR}}/../../:${{vars.CFITSIO_DIR}}/lib" >> $GITHUB_ENV
          shortSha=$(git rev-parse --short ${{github.sha}})
          echo "COMMIT_SHORT_SHA=$shortSHA" >> GITHUB_ENV
          cp ${{github.workspace}}/Code/icons/visivo.svg ViaLacteaVisualAnalytics.svg
      
      - name: Create AppDir
        run: >
          linuxdeploy
          --appdir AppDir
          -e ViaLacteaVisualAnalytics
          --create-desktop-file
          -i ViaLacteaVisualAnalytics.svg
          --plugin qt
      
      - name: Fix AppDir
        run: |
          rm AppDir/usr/lib/libnss*
          cp -r ${{github.workspace}}/Utils/* AppDir/usr/bin
          sed -i "/exec/s/\$$/ --no-sandbox/" AppDir/AppRun

      - name: Create AppImage
        run: |
          appimagetool "AppDir" ViaLacteaVisualAnalytics-${{env.COMMIT_SHORT_SHA}}-x86_64.AppImage

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: continuous
          prerelease: true
          files: |
            ViaLacteaVisualAnalytics-${{env.COMMIT_SHORT_SHA}}-x86_64.AppImage
          token: ${{secrets.GITHUB_TOKEN}}
