name: CI/CD
run-name: Releasing ${{github.ref_name}}

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build:
    runs-on: [self-hosted, linux, x64]

    steps:       
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Code

      - name: Setup
        env:
          KEYS: ${{secrets.KEYS}}
        run: echo $KEYS | base64 -d > Code/src/authkeys.h

      - name: Configure
        run: > 
          cmake
          -G Ninja
          -S ${{github.workspace}}/Code
          -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE:STRING="Release"
          -DCMAKE_PREFIX_PATH:PATH=${{vars.Qt5_DIR}}
          -DCMAKE_CXX_FLAGS_INIT:STRING="-fuse-ld=gold"
          -DVTK_DIR:PATH=${{vars.VTK_DIR}}
          -DCFITSIO_ROOT_DIR:PATH=${{vars.CFITSIO_DIR}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --parallel
      
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: Binary
          path: ${{github.workspace}}/build/ViaLacteaVisualAnalytics
          retention-days: 1

  release:
    needs: build
    runs-on: [self-hosted, linux, x64]

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Code
            Utils
      
      - name: Get binary
        uses: actions/download-artifact@v4
        with:
          name: Binary
      
      - name: Setup
        shell: bash
        run: |
          echo "${{vars.Qt5_DIR}}/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=${{vars.VTK_DIR}}/../../:${{vars.CFITSIO_DIR}}/lib" >> $GITHUB_ENV
          cp ${{github.workspace}}/Code/icons/visivo.svg ViaLacteaVisualAnalytics.svg
          cp ${{github.workspace}}/Code/ViaLacteaVisualAnalytics.desktop ViaLacteaVisualAnalytics.desktop
      
      - name: Create AppDir
        run: >
          linuxdeploy
          --appdir AppDir
          -e ViaLacteaVisualAnalytics
          -l /usr/lib/x86_64-linux-gnu/libssl.so.1.1
          -d ViaLacteaVisualAnalytics.desktop
          -i ViaLacteaVisualAnalytics.svg
          --plugin qt
      
      - name: Fix AppDir
        run: |
          rm -f AppDir/usr/lib/libnss*
          cp -r ${{github.workspace}}/Utils/* AppDir/usr/bin
          sed -i "/exec/s/\$$/ --no-sandbox/" AppDir/AppRun

      - name: Create AppImage
        run: |
          appimagetool "AppDir" ViaLacteaVisualAnalytics-${{github.ref_name}}-x86_64.AppImage

      - name: Create deb package
        if: ${{github.ref_type == 'tag'}}
        run: |
          mkdir -p ViaLacteaVisualAnalytics-${{github.ref_name}}-amd64/opt/ViaLacteaVisualAnalytics ViaLacteaVisualAnalytics-${{github.ref_name}}-amd64/usr/share/applications ViaLacteaVisualAnalytics-${{github.ref_name}}-amd64/usr/share/icons/hicolor/scalable/apps
          mv AppDir/usr/* ViaLacteaVisualAnalytics-${{github.ref_name}}-amd64/opt/ViaLacteaVisualAnalytics
          mv ViaLacteaVisualAnalytics.desktop ViaLacteaVisualAnalytics-${{github.ref_name}}-amd64/usr/share/applications
          mv ViaLacteaVisualAnalytics.svg ViaLacteaVisualAnalytics-${{github.ref_name}}-amd64/usr/share/icons/hicolor/scalable/apps
          echo ${{vars.DEBIAN}} | base64 -d | tar xzf - -C ViaLacteaVisualAnalytics-${{github.ref_name}}-amd64
          sed -i "s/.*Version:.*/Version: ${{github.ref_name}}/" ViaLacteaVisualAnalytics-${{github.ref_name}}-amd64/DEBIAN/control
          dpkg-deb --build --root-owner-group ViaLacteaVisualAnalytics-${{github.ref_name}}-amd64

      - name: Publish continuous release
        if: ${{github.ref_type == 'branch'}}
        run: |
          pyuploadtool ViaLacteaVisualAnalytics-${{github.ref_name}}-x86_64.AppImage
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish release
        if: ${{github.ref_type == 'tag'}}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{github.ref_name}}
          generate_release_notes: true
          make_latest: true
          files: |
            ViaLacteaVisualAnalytics-${{github.ref_name}}-x86_64.AppImage
            ViaLacteaVisualAnalytics-${{github.ref_name}}-amd64.deb
          token: ${{secrets.GITHUB_TOKEN}}
